version: '3.4'

services:
  OktaSampleApi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=62513
      - CERTIFICATE_KEY=OktaSampleApi
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=password
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/OktaSampleApi.pfx
      - AZURE_CLIENT_ID=d4fbe55f-9057-4040-9c86-87e4713b4ad4
      - AZURE_CLIENT_SECRET=9fe9fe9c-74c8-46ce-8110-033a17078817
      - AZURE_TENANT_ID=c72062b3-4200-4fb6-81d5-77d93e65d325
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=OktaSampleCommon

    ports:
      - "62514:80"
      - "62513:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/https:ro
      - ~/.aspnet/https:/https:ro
  OktaSampleWeb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=62516
      - CERTIFICATE_KEY=OktaSampleWeb
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=password
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/OktaSampleWeb.pfx
      - AZURE_CLIENT_ID=d4fbe55f-9057-4040-9c86-87e4713b4ad4
      - AZURE_CLIENT_SECRET=9fe9fe9c-74c8-46ce-8110-033a17078817
      - AZURE_TENANT_ID=c72062b3-4200-4fb6-81d5-77d93e65d325
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=OktaSampleCommon
      - WeatherSettings__BaseAddress=https://OktaSampleApi
    ports:
      - "62517:80"
      - "62516:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/https:ro
      -  ~/.aspnet/https:/https:ro
